package com.droider.droiderposconnectorlibrary;

public interface DroiderConstant {

    String DESTINATION_PACKAGE_NAME = "com.hbl.centerm";
    String DESTINATION_INPUT_MONEY_ACTIVITY = "com.app.centerm.view.activities.InputMoneyActivity";
    String DESTINATION_SETTLEMENT_ACTIVITY = "com.app.centerm.view.activities.SettlementActivity";
    String DESTINATION_VOID_ACTIVITY = "com.app.centerm.view.activities.VoidActivity";

    String DROIDER = "DROIDER";
    String DROIDER_APPLICATION_NAME = "DROIDER_APPLICATION_NAME";
    String DROIDER_APPLICATION_NAME_SILVER_LINE = "DROIDER_APPLICATION_NAME_SILVER_LINE";
    String DROIDER_AMOUNT = "DROIDER_AMOUNT";
    String DROIDER_APPLICATION_PACKAGE_NAME = "DROIDER_APPLICATION_PACKAGE_NAME";
    String DROIDER_APPLICATION_ACTIVITY_NAME = "DROIDER_APPLICATION_ACTIVITY_NAME";

    String DROIDER_TRANSACTION_STATUS = "DROIDER_TRANSACTION_STATUS";
    String DROIDER_TRANSACTION_STATUS_SUCCESS = "Transaction Success";
    String DROIDER_TRANSACTION_STATUS_FAILURE = "Transaction Failed";
    String DROIDER_TRANSACTION_RESPONSE_CODE = "DROIDER_TRANSACTION_RESPONSE_CODE";

    //TYPE OF TRANSACTION
    String DROIDER_TRANSACTION_TYPE = "DROIDER_TRANSACTION_TYPE";
    String DROIDER_SETTLEMENT_TRANSACTION = "DROIDER_SETTLEMENT_TRANSACTION";
    String DROIDER_VOID_TRANSACTION = "DROIDER_VOID_TRANSACTION";
    String DROIDER_SALE_TRANSACTION = "DROIDER_SALE_TRANSACTION";
    String DROIDER_SALE_WITH_QR_TRANSACTION = "DROIDER_SALE_WITH_QR_TRANSACTION";
}
